language: rust
cache: cargo
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test -- --test-threads=1
