language: rust
services:
  - redis-server
cache: cargo
rust:
  - nightly-2018-07-14
branches:
  only:
    - master
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --check
  - cargo b
  - ./tdb
  - cargo doc --no-deps
  - ./scripts/gh-pages.sh
