[package]
name = "fxa_email_service"
version = "1.115.0"
publish = false

[[bin]]
name = "fxa-email-service"
path = "src/bin/service.rs"

[[bin]]
name = "fxa-email-queues"
path = "src/bin/queues.rs"

[dependencies]
base64 = ">=0.6.0"
chrono = { version = ">=0.4.2", features = [ "serde" ] }
config = ">=0.8.0"
emailmessage = ">=0.1.0"
failure = ">=0.1.1"
futures = ">=0.1.21,<0.2"
hex = ">=0.3.2"
hmac = ">=0.6.2"
lazy_static = ">=1.0"
md5 = ">=0.3.7"
mozsvc-common = ">=0.1.0"
rand = ">=0.5.1"
redis = ">=0.8.0"
regex = ">=1.0"
reqwest = ">=0.8.5"
rocket = ">=0.3.14"
rocket_codegen = ">=0.3.14"
rocket_contrib = ">=0.3.14"
rusoto_core = ">=0.32.0"
rusoto_credential = ">=0.11.0"
rusoto_ses = ">=0.32.0"
rusoto_sqs = ">=0.32.0"
sendgrid = ">=0.7.1"
serde = ">=1.0"
serde_derive = ">=1.0"
serde_json = ">=1.0"
serde_test = ">=1.0.66"
sha2 = ">=0.7.1"
slog = ">=2.2.3"
slog-async = ">=2.3.0"
slog-mozlog-json = ">=0.1.0"
slog-term = ">=2.4.0"
