[package]
name = "fxa-email-service"
version = "0.1.0"

[dependencies]
config = "0.8.0"
lazy_static = "1.0"
regex = "0.2.10"
rocket = "0.3.10"
rocket_codegen = "0.3.10"
rocket_contrib = "0.3.10"
rusoto_core = "0.32.0"
rusoto_credential = "0.11.0"
rusoto_ses = "0.32.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
validator = "0.6.3"
validator_derive = "0.6.5"
