(function() {var implementors = {};
implementors["fxa_email_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"fxa_email_service/app_errors/enum.AppErrorKind.html\" title=\"enum fxa_email_service::app_errors::AppErrorKind\">AppErrorKind</a>",synthetic:false,types:["fxa_email_service::app_errors::AppErrorKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"struct\" href=\"fxa_email_service/delivery_problems/struct.DeliveryProblem.html\" title=\"struct fxa_email_service::delivery_problems::DeliveryProblem\">DeliveryProblem</a>",synthetic:false,types:["fxa_email_service::delivery_problems::DeliveryProblem"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"fxa_email_service/delivery_problems/enum.ProblemType.html\" title=\"enum fxa_email_service::delivery_problems::ProblemType\">ProblemType</a>",synthetic:false,types:["fxa_email_service::delivery_problems::ProblemType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"fxa_email_service/delivery_problems/enum.ProblemSubtype.html\" title=\"enum fxa_email_service::delivery_problems::ProblemSubtype\">ProblemSubtype</a>",synthetic:false,types:["fxa_email_service::delivery_problems::ProblemSubtype"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"struct\" href=\"fxa_email_service/email_address/struct.EmailAddress.html\" title=\"struct fxa_email_service::email_address::EmailAddress\">EmailAddress</a>",synthetic:false,types:["fxa_email_service::email_address::EmailAddress"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
