(function() {var implementors = {};
implementors["fxa_email_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"fxa_email_service/auth_db/enum.BounceType.html\" title=\"enum fxa_email_service::auth_db::BounceType\">BounceType</a>",synthetic:false,types:["fxa_email_service::auth_db::BounceType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"fxa_email_service/auth_db/enum.BounceSubtype.html\" title=\"enum fxa_email_service::auth_db::BounceSubtype\">BounceSubtype</a>",synthetic:false,types:["fxa_email_service::auth_db::BounceSubtype"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"fxa_email_service/db/enum.DataType.html\" title=\"enum fxa_email_service::db::DataType\">DataType</a>",synthetic:false,types:["fxa_email_service::db::DataType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"fxa_email_service/queues/sqs/notification/enum.NotificationType.html\" title=\"enum fxa_email_service::queues::sqs::notification::NotificationType\">NotificationType</a>",synthetic:false,types:["fxa_email_service::queues::sqs::notification::NotificationType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"fxa_email_service/queues/sqs/notification/enum.BounceType.html\" title=\"enum fxa_email_service::queues::sqs::notification::BounceType\">BounceType</a>",synthetic:false,types:["fxa_email_service::queues::sqs::notification::BounceType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"fxa_email_service/queues/sqs/notification/enum.BounceSubtype.html\" title=\"enum fxa_email_service::queues::sqs::notification::BounceSubtype\">BounceSubtype</a>",synthetic:false,types:["fxa_email_service::queues::sqs::notification::BounceSubtype"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"fxa_email_service/queues/sqs/notification/enum.ComplaintFeedbackType.html\" title=\"enum fxa_email_service::queues::sqs::notification::ComplaintFeedbackType\">ComplaintFeedbackType</a>",synthetic:false,types:["fxa_email_service::queues::sqs::notification::ComplaintFeedbackType"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
