(function() {var implementors = {};
implementors["fxa_email_service"] = [{text:"impl&lt;'v&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;&amp;'v <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"fxa_email_service/types/duration/struct.Duration.html\" title=\"struct fxa_email_service::types::duration::Duration\">Duration</a>",synthetic:false,types:["fxa_email_service::types::duration::Duration"]},{text:"impl&lt;'v&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;&amp;'v <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"enum\" href=\"fxa_email_service/types/env/enum.Env.html\" title=\"enum fxa_email_service::types::env::Env\">Env</a>",synthetic:false,types:["fxa_email_service::types::env::Env"]},{text:"impl&lt;'v&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;&amp;'v <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"enum\" href=\"fxa_email_service/types/logging/enum.LogLevel.html\" title=\"enum fxa_email_service::types::logging::LogLevel\">LogLevel</a>",synthetic:false,types:["fxa_email_service::types::logging::LogLevel"]},{text:"impl&lt;'v&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;&amp;'v <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"enum\" href=\"fxa_email_service/types/logging/enum.LogFormat.html\" title=\"enum fxa_email_service::types::logging::LogFormat\">LogFormat</a>",synthetic:false,types:["fxa_email_service::types::logging::LogFormat"]},{text:"impl&lt;'v&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;&amp;'v <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"enum\" href=\"fxa_email_service/types/provider/enum.Provider.html\" title=\"enum fxa_email_service::types::provider::Provider\">Provider</a>",synthetic:false,types:["fxa_email_service::types::provider::Provider"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
