(function() {var implementors = {};
implementors["fxa_email_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"fxa_email_service/app_errors/struct.AppError.html\" title=\"struct fxa_email_service::app_errors::AppError\">AppError</a>",synthetic:false,types:["fxa_email_service::app_errors::AppError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"fxa_email_service/app_errors/enum.AppErrorKind.html\" title=\"enum fxa_email_service::app_errors::AppErrorKind\">AppErrorKind</a>",synthetic:false,types:["fxa_email_service::app_errors::AppErrorKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"fxa_email_service/duration/struct.DurationError.html\" title=\"struct fxa_email_service::duration::DurationError\">DurationError</a>",synthetic:false,types:["fxa_email_service::duration::DurationError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"fxa_email_service/message_data/struct.MessageDataError.html\" title=\"struct fxa_email_service::message_data::MessageDataError\">MessageDataError</a>",synthetic:false,types:["fxa_email_service::message_data::MessageDataError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"fxa_email_service/queues/sqs/notification/enum.NotificationType.html\" title=\"enum fxa_email_service::queues::sqs::notification::NotificationType\">NotificationType</a>",synthetic:false,types:["fxa_email_service::queues::sqs::notification::NotificationType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"fxa_email_service/queues/struct.QueueError.html\" title=\"struct fxa_email_service::queues::QueueError\">QueueError</a>",synthetic:false,types:["fxa_email_service::queues::QueueError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
